# Generated by Django 3.1.6 on 2021-02-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_des', models.CharField(max_length=300)),
                ('product_date', models.DateField()),
            ],
        ),
    ]
