# Generated by Django 3.1.6 on 2021-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210228_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=150)),
                ('contact_phone', models.DateField(max_length=15)),
                ('contact_subject', models.CharField(max_length=200)),
                ('contact_desc', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
