# Generated by Django 3.1.6 on 2021-08-08 01:31

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210330_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('JSON_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
