# Generated by Django 3.1.6 on 2021-08-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210808_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_desc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
