# Generated by Django 3.1.6 on 2021-09-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
