# Generated by Django 3.1.6 on 2021-09-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210909_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='orderid',
            new_name='order_id',
        ),
    ]
